Added Brew to dotfiles

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,6 +10,13 @@ echo ''
 echo ''
 echo 'Beginning dotfiles installation'
 
+if ! [ -x "$(command -v brew)" ]; then
+  echo 'Error: homebrew is not installed.' >&2
+  exit 1
+fi
+
+brew bundle
+
 # find the installers and run them iteratively
 for installer in $(find . -name "*install.sh"); do
   echo ''
